#
#  Argus Clients Software
#  Copyright (c) 2000-2016 QoSient, LLC
#  All rights reserved.
#
#  QOSIENT, LLC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS
#  SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
#  AND FITNESS, IN NO EVENT SHALL QOSIENT, LLC BE LIABLE FOR ANY
#  SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
#  IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
#  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
#  THIS SOFTWARE.
#
#
#  Services fingerprint file, generated by:
#      rauserdata -d16 -e encode32
#
#  with modifications.
#

Service: ftp             tcp port 21    n =  1043 src = "32323020                        "
Service: ftp             tcp port 21    n =   158 src = "5553455220616E6F6E796D6F75730D0A"
Service: ftp             tcp port 21    n =    60 src = "6100610061000000"
Service: ftp             tcp port 21    n =     4 src = "455F00  000000000000      6D    "
Service: ftp             tcp port 21    n =     2 src = "2A01    00  0000000100010008    "
Service: ftp             tcp port 21    n =   158 dst = "3232302D                        "
Service: ftp             tcp port 21    n =    60 dst = "32323020                        "
Service: ftp             tcp port 21    n =     4 dst = "455F00    00  00  00  00  00  00"
Service: ftp             tcp port 21    n =     2 dst = "2A01    0004000000012A04    0123"

Service: ssh             tcp port 22    n =    12 src = "5353482D  2E  2D4F70656E5353485F"  encrypted
Service: ssh             tcp port 22    n =    12 dst = "5353482D312E              53    "

Service: telnet          tcp port 23    n =    79 src = "FFFB25FF    FF    FFFD  FF      "  encrypted
Service: telnet          tcp port 23    n =    79 dst = "FFFB25FF    FF    FFFD  FF      "  encrypted
Service: telnet          tcp port 23    n =    59 src = "FFFB25FF    FF    FF    FF    FF"
Service: telnet          tcp port 23    n =    32 src = "FFFB25FF    FF    FFFD  FF    FF"
Service: telnet          tcp port 23    n =    11 src = "FFFB25FFFB26FFFD03FFFD01FFFB1FFF"
Service: telnet          tcp port 23    n =    13 src = "FFFD01FFFD03FFFB18FFFC1F        "
Service: telnet          tcp port 23    n =     8 src = "FFFB25FFFD26FFFB26FFFD03FFFB18FF"
Service: telnet          tcp port 23    n =     7 src = "FFFB25FFFD26FFFB26FFFD03FFFB18FF"
Service: telnet          tcp port 23    n =     6 src = "F8F821216F6F5454F3F36565A4A4AEAE"
Service: telnet          tcp port 23    n =     5 src = "FFFB25FFFD26FFFB26FFFD03FFFB18FF"
Service: telnet          tcp port 23    n =     4 src = "FFFB25FFFD26FFFB26FFFD03FFFB18FF"
Service: telnet          tcp port 23    n =     4 src = "FF    FF    FFFB  FF    FF    FF"
Service: telnet          tcp port 23    n =     4 src = "FFFB25FFFD26FFFB26FFFD03FFFB18FF"
Service: telnet          tcp port 23    n =     4 src = "FFFB25FF  26FF    FFFD  FFFB  FF"

Service: smtp            tcp port 25    n =   442 src = "45484C4F20                      "  dst = "32323020                        "
Service: smtp            tcp port 25    n =    35 src = "45484C4F206E6577796F726B2E716F73"  dst = "3232302D                        "
Service: smtp            tcp port 25    n =     7 src = "48454C4F206D61696C2E            "  dst = "32323020                        "

Service: time            udp port 37    n =    16 src = "00000000000000000000000000000000"  dst = "BF47    "

Service: name            udp port 42    n =    23 src = "CDAB000000000000C0A8001000000000"
Service: nicname         tcp port 43    n =   100 src = ""                                  dst = ""

Service: domain          udp port 53    n = 33972 src = "    01000001000000000000055F6C64"  dst = "    85  000100  00  00          "
Service: domain          udp port 53    n = 22448 src = "      000001000000000000        "  dst = "      80000100  00  00          "
Service: domain          tcp port 53    n =    41 src = "00      0000000100010000000000  "  dst = "000C    80  000000000000000000  "

Service: bootps          udp port 67    n = 18188 src = "01010600        0A008000C0A80010"  dst = "02010600        00008000C0A80010"
Service: finger          tcp port 79    n =     4 src = "6C696A756E2E74616E670D0A"          dst = "4C6F67696E202020202020204E616D65"
Service: finger          tcp port 79    n =     3 src = "        61    0D0A000000"          dst = "0D0A5B20466F7277617264696E6720  "

Service: http            tcp port 80   n = 257580 src = "474554202F                      "  dst = "485454502F312E  20              "
Service: http            tcp port 80    n = 11806 src = "48454144202F                    "  dst = "485454502F312E  20  30  20      "
Service: http            tcp port 80    n =  3344 src = "4F5054494F4E53202F20485454502F31"  dst = "485454502F312E  20323030204F4B0D"
Service: http            tcp port 80    n =  5433 src = "504F535420                      "  dst = "485454502F312E  20              "
Service: http            tcp port 80    n =   666 src = "504F5354202F                    "  dst = "485454502F312E  20  30  20      "
Service: http            tcp port 80    n =   425 dst = "474946383961      00    00      "
Service: http            tcp port 80    n =   173 dst = "          485454502F312E  20  30"
Service: http            tcp port 80    n =    44 dst = "3C68746D6C3E                    "
Service: http            tcp port 80    n =    34 src = "50524F5046494E44202F737973766F6C"  dst = "485454502F312E312034303420526573"

Service: kerberos        udp port 88    n = 18105 src = "6A8201423082013EA103020105A20302"  dst = "7E8201  308201  A003020105A10302"
Service: kerberos        udp port 88    n =     2 src = "040748414E445245572E434D552E4544"  dst = "0404746F680000003B9D1C  013B9D8C"
Service: kerberos        udp port 88    n =     2 src = "6A81B23081AFA103020105A20302010A"  dst = "6B8202103082020CA003020105A10302"

Service: pop3            tcp port 110   n = 73424 src = "55534552                        "  dst = "2B4F4B20                        "
Service: pop3            tcp port 110   n = 52481 src = "55534552                        "  dst = "2B4F4B0D0A                      "
Service: pop3            tcp port 110   n = 35377 src = "55534552206368656C6C79617A0D0A50"  dst = "2B4F4B20496E7465724D61696C20504F"
Service: pop3            tcp port 110   n =  3091 src = "434150410D0A5553455220          "  dst = "2B4F4B                          "
Service: pop3            tcp port 110   n =   873 src = "5041535320                      "  dst = "2B4F4B                          "
Service: pop3            tcp port 110   n =   808 src = "41504F5020                      "  dst = "                                "
Service: pop3            tcp port 110   n =   553 src = "7463705F636C6F73652C20647572696E"  dst = "                                "
Service: pop3            tcp port 110   n =   472 src = "4155544820                      "  dst = "                                "
Service: pop3            tcp port 110   n =   126 src = "7573657220                      "  dst = "2B4F4B20                        "
Service: pop3            tcp port 110   n =    74 src = "535441540D0A                    "  dst = "2B4F4B                          "
Service: pop3            tcp port 110   n =    68 src = "415554480D0A41555448204C4F47494E"  dst = "2B4F4B                          "
Service: pop3            tcp port 110   n =    33 src = "515549540D0A0000                "  dst = "2B4F4B203020300D0A2B4F4B20      "
Service: pop3            tcp port 110   n =    29 src = "636170610D0A61706F7020          "  dst = "2B4F4B                          "
Service: pop3            tcp port 110   n =     6 src = "6E6F207463702C207265736574000000"  
Service: pop3            tcp port 110   n =     6 src = "2A01        00000001            "  dst = "2A01    0004000000012A02    00  "
Service: pop3            tcp port 110   n =     3 src = "5245545220310D0A"  
Service: pop3            tcp port 110   n =     3 src = "4E6F205443502F4E6F206C697374656E"  
Service: pop3            tcp port 110   n =     3 src = "5549444C0D0A    444C0D0A51554954"  dst = "2B4F4B                          "
Service: pop3            tcp port 110   n =     2 src = "7463705F646973636F6E6E656374    "  dst = "2B4F4B                          "
Service: pop3            tcp port 110   n =     2 src = "5549444C20310D0A5549444C0D0A    "  dst = "2B4F4B                          "

Service: sunrpc          udp port 111   n =   541 src = "3D      00000000000000  00      "  dst = "3D      000000  0000000000000000"
Service: sunrpc          udp port 111   n =   175 src = "        0000000000000002000186A0"  
Service: sunrpc          tcp port 111   n =    28 src = "800000          0000000000000002"  dst = "8000001C        0000000100000000"
Service: sunrpc          udp port 111   n =    18 src = "3D      00000000000000  00      "  dst = "3D      000000  0000000000000000"
Service: sunrpc          udp port 111   n =     2 src = "3D85    000000000000000000000000"  dst = "3D85    000000000000000000000000"


Service: ident           tcp port 113   n =    15 src = "3438    2C32350D0A000000        "  dst = "3438    202C203235203A2055534552"
Service: ident           tcp port 113   n =    11 src = "313032332C3531340D0A0000        "  dst = "31303233202C20353134203A20555345"
Service: ident           tcp port 113   n =    12 src = "        202C20353333350D0A000000"  dst = "                                "
Service: ident           tcp port 113   n =     6 src = "    35          0D0A0000"          "32383534202C20313139203A20555345"
Service: ident           tcp port 113   n =     5 src = "  37    202C2032350D0A00"  dst = "3233    202C203235203A2055534552"


Service: nntp            tcp port 119   n =    75 src = "6D6F64652073747265616D0D0A636865"  dst = "32303020                    65  "
Service: nntp            tcp port 119   n =    20 src = "4D4F444520            0D0A      "  dst = "3230  206E6E74702E6563652E636D75"
Service: nntp            tcp port 119   n =    11 src = "6968617665203C                  "  dst = "32303020686F6E65797375636B6C652E"
Service: nntp            tcp port 119   n =     4 src = "636865636B203C                  "  dst = "32303020686F6E65797375636B6C652E"

Service: ntp             udp port 123   n = 15209 src = "        0000    00              "  dst = "        0000    0000            "
Service: ntp             udp port 123   n =  6414 src = "    0AFA                    00  "  dst = "1A020AF900000000        C0A80080"
Service: ntp             udp port 123   n =  4175 src = "23    F10000    00              "  dst = "        000000000000            "
Service: ntp             udp port 123   n =  4183 src = "23    F10000    00              "  dst = "24    EE0000    0000            "
Service: ntp             udp port 123   n =  7775 src = "23020AEF0000    0000    82CFF4F0"  dst = "24010A  000000000000    55534E4F"
Service: ntp             udp port 123   n =  2002 src = "1B030AEE0000    000004  A55BFAD6"  dst = "1C030A  000017  0000    8002BF46"
Service: ntp             udp port 123   n =   364 src = "  00    00  000000  000000000000"  dst = "  0304  0000    0000    8002    "
Service: ntp             udp port 123   n =    51 src = "  03    0000    0000    C0A800  "  dst = "  02  EF0000    0000    C0052928"
Service: ntp             udp port 123   n =    14 src = "2302  EF0000    0000    80762E03"  dst = "24      0000    0000    80      "

Service: outlook         tcp port 0     n = 12672 src = "05000B0310000000              00"  dst = "0500  0310000000            0000"

Service: nfsd-status     tcp port 1110  n =     2 src = "4155544856302E316A7573746A756E6B"  dst = "2B4F4B2051504F50202876657273696F"

Service: netbios-ns      udp port 137   n =  1925 src = "    0100000100000000000020464245"  dst = "    8583000000000000000020464245"
Service: netbios-ns      udp port 137   n =   135 src = "      00000100000000000020      "  dst = "        000000  0000000020      "
Service: netbios-dgm     udp port 138   n =  2345 src = "        C0A800  008A    00002046"  dst = "  0E    C0A800  008A    00002046"
Service: netbios-ssn     tcp port 139   n =   252 src = "810000442046  46                "  dst = "82000000"
Service: netbios-ssn     tcp port 139   n =     4 src = "810000442045  45                "  dst = "82000000000000  FF534D4272000000"

Service: imap            tcp port 143   n = 48745 src = "444F4E450D0A                    "  dst = "        204F4B2049444C4520636F6D"
Service: imap            tcp port 143   n = 36835 src = "        204341504142494C4954590D"  dst = "        20                636F6D"
Service: imap            tcp port 143   n =  2636 src = "444F4E450D0A                    "  dst = "2A20                            "
Service: imap            tcp port 143   n =   332 src = "444F4E450D0A                    "  dst = "2A2042594520                    "
Service: imap            tcp port 143   n =   265 src = "444F4E450D0A    "                  dst = "2A20    204558495354530D0A2A20  "
Service: imap            tcp port 143   n =   279 src = "        2049444C450D0A          "  dst = "2B20526561647920666F722061726775"
Service: imap            tcp port 143   n =    48 src = "        2049444C450D0A  "          dst = "    4C      2028          20    "
Service: imap            tcp port 143   n =   118 src = "        2055494420              "  dst = "        204F4B20                "
Service: imap            tcp port 143   n =     1 src = "303130392049444C450D0A00"          dst = "7474703A2F2F7777772E73616C657372"
Service: imap            tcp port 143   n =    97 src = "        2049444C450D0A          "  dst = "          2046        2028      "
Service: imap            tcp port 143   n =     2 src = "303142362049444C450D0A444F4E450D"  dst = "      20                656365  "
Service: imap            tcp port 143   n =     3 src = "30315156205549442046455443482031"  dst = "  20      20    7572            "
Service: imap            tcp port 143   n =     9 src = "                                "  dst = "                  20323039      "
Service: imap            tcp port 143   n =     2 src = "3031534D2049444C450D0A00"          dst = "20        20    20            30"
Service: imap            tcp port 143   n =     1 src = "30315432205549442053544F52452032"  dst = "41475320285C526563656E742920424F"
Service: imap            tcp port 143   n =   132 src = "        2049444C450D0A          "  dst = "        204F4B20                "
Service: imap            tcp port 143   n =     3 src = "30      2055494420464554434820  "  dst = "                    6F    656E74"
Service: imap            tcp port 143   n =     8 src = "        2049444C450D0A444F4E450D"  dst = "        2046        2028        "
Service: imap            tcp port 143   n =     1 src = "30303058205549442046455443482031"  dst = "4633323444392E463642220D0A582D50"
Service: imap            tcp port 143   n =    19 src = "        2049444C450D0A          "  dst = "  20                    0D0A  20"
Service: imap            tcp port 143   n =   122 src = "444F4E450D0A                    "  dst = "2B20526561647920666F722061726775"
Service: imap            tcp port 143   n =     2 src = "                                "  dst = "      73              616E  20  "
Service: imap            tcp port 143   n =    54 src = "30      2053          2022      "  dst = "2A2053544154555320              "
Service: imap            tcp port 143   n =    44 src = "        2049444C450D0A          "  dst = "2A2053544154555320224A756E6B2045"
Service: imap            tcp port 143   n =    27 src = "        2049444C450D0A          "  dst = "                    20  30392046"
Service: imap            tcp port 143   n =     9 src = "        2055494420464554434820  "  dst = "2A2032    20                    "
Service: imap            tcp port 143   n =     8 src = "        2055494420464554434820  "  dst = "2A20    20                  20  "
Service: imap            tcp port 143   n =     2 src = "3030304F204E4F4F500D0A3030305020"  dst = "                      20627920  "
Service: imap            tcp port 143   n =     2 src = "303030532049444C450D0A00"          dst = "6365697665643A20              39"
Service: imap            tcp port 143   n =     1 src = "303053342049444C450D0A00"          dst = "6D2D326636393365376340716F736965"
Service: imap            tcp port 143   n =     1 src = "30313730205549442046455443482037"  dst = "7970746F6772617068793E20616C7761"
Service: imap            tcp port 143   n =     1 src = "3033305A2049444C450D0A00"          dst = "636F6D3E0D0A5265706C792D546F3A20"

Service: snmp            udp port 161   n =   368 src = "30  02010004                    "  dst = "30  02010004                    "
Service: snmp            udp port 161   n =    88 src = "308200  0201000407326B65776C3475"  dst = "30  0201000407326B65776C3475A2  "
Service: snmp            udp port 161   n =     3 src = "3081880201000407326B65776C3475A0"  dst = "3081950201000407326B65776C3475A2"

Service: ldap            udp port 389   n =  4338 src = "3084000000EE0202    6384000000E4"  dst = "3084000000110202    658400000007"
Service: ldap            tcp port 389   n =   302 src = "30840000    02          00      "  dst = "30840000    02          00      "

Service: imsp            tcp port 406   n =    32 src = "413030303031204341504142494C4954"  dst = "2A204F4B20437972757320494D535020"

Service: synoptics-trap  tcp port 412   n =    41 src = "244D794E69636B206A6F6D626C65727C"  dst = "244D794E69636B206864696E6765727C"
Service: synoptics-trap  udp port 412   n =    75 src = "24535220  64                    "  dst = "2450696E67200000"
Service: synoptics-trap  udp port 412   n =    27 src = "24535220                20      "  dst = "2450696E67200000"
Service: synoptics-trap  udp port 412   n =    11 src = "24535220                      65"  dst = "2450696E67200000"
Service: synoptics-trap  udp port 412   n =    10 src = "24535220  61              2053  "  dst = "2450696E67200000"
Service: synoptics-trap  udp port 412   n =     7 src = "24535220                61      "  dst = "2450696E67200000"
Service: synoptics-trap  udp port 412   n =     4 src = "24535220        64    6E        "  dst = "2450696E67200000"
Service: synoptics-trap  udp port 412   n =     2 src = "24535220          20            "  dst = "2450696E67200000"

Service: svrloc          udp port 427   n =   542 src = "02010000312000000000    0002656E"  
Service: svrloc          udp port 427   n =     1 src = "0107012D0000656E000300000000011D"  

Service: https           tcp port 443   n =  2336 src = "160300005D010000590300          "  encrypted
Service: https           tcp port 443   n =   365 src = "8046010300002D00000010010080  00"  
Service: https           tcp port 443   n =   339 src = "807A0103010051000000200000160000"  
Service: https           tcp port 443   n =    45 src = "1403  0001011603  00            "  
Service: https           tcp port 443   n =    19 src = "17030001FDF718A4165E3DE84936DD30" 
Service: https           tcp port 443   n =     6 src = "    474554202F                  "  
Service: https           tcp port 443   n =     1 src = "807A0103010051000000200000160000"  

Service: microsoft-ds    tcp port 445   n =  3161 src = "000000    534D4272000000001853C8"  dst = "000000B6FF534D4272000000009853C8"

Service: syslog          udp port 514   n =   121 src = "3C                              "  

Service: shell           tcp port 514   n =  1241 src = "313032  00726F6F7400726F6F740072"  dst = "00560A050A050A050A593430393620  "
Service: shell           tcp port 514   n =     4 src = "3130323200  6F                  "  dst = "00      2041707220    20    3A32"
Service: shell           tcp port 514   n =     3 src = "00716F7369656E7400              "  dst = "00433036343420323830373120737464"
Service: shell           tcp port 514   n =     2 src = "3130323200  6F                  "  dst = "006368617267656E0A6368617267656E"
Service: shell           tcp port 514   n =     2 src = "313032  00  6F                  "  dst = "00              2F0A            "
Service: shell           tcp port 514   n =     2 src = "00  6F                          "  dst = "00000000                        "

Service: ntalk           udp port 518   n =     2 src = "01010000000000000002000000000000"  dst = "010101  00000000                "

Service: router          udp port 520   n = 52906 src = "0101000000  00000000000000000000"
Service: router          udp port 520   n =    62 src = "  01000000  0000      0000000000"  
Service: router          udp port 520   n =    53 src = "  01000000  00000000000000000000"  
Service: router          udp port 520   n =    19 src = "0201000000  0000      0000000000"  
Service: router          udp port 520   n =    19 src = "0202000000  0000      00    0000" 

Service: rtsp            tcp port 554   n =     6 src = "4F5054494F4E5320727473703A2F2F  "  dst = "525453502F312E3020323030204F4B0D"
Service: rtsp            tcp port 554   n =     2 src = "474554202F696D616765732F6F6E652E"  dst = "485454502F312E3120  30  20      "

Service: ntam            tcp port 561   n =   470 src = "                                "  dst = "0104    00  08  C0A800A2003F    "
Service: ntam            tcp port 561   n =   158 src = "                                "  dst = "801000  00  0000E5            "
Service: ntam            tcp port 561   n =   114 src = "7B31307D0D0A4449474553542D4D4435"  dst = "8001008000900000E5617ACB00000000"
Service: ntam            tcp port 561   n =    20 src = "                                "  dst = "800100  00800000E5617ACB00000000"
Service: ntam            tcp port 561   n =    38 src = "                                "  dst = "0104    009008  C0A800A20032C0  "
Service: ntam            tcp port 561   n =    32 src = "46494C5445523A206D616E206F722028"  dst = "8010002000000000E5              "
Service: ntam            tcp port 561   n =    13 src = "4F5054494F4E53202F20  54  502F31"  dst = "8010002000000000E5      000CCF86"
Service: ntam            tcp port 561   n =     7 src = "474554202F20485454502F312E300D0A"  dst = "8010002000000000E5      000CCF86"
Service: ntam            tcp port 561   n =     7 src = "010000FDCEFA0BB0A00000004D4D5314"  dst = "8010002000000000E5      000CCF86"
Service: ntam            tcp port 561   n =     7 src = "010000FDCEFA0BB0A00000004D4D5314"  dst = "8010002000000000E5      000CCF86" 
 
Service: nntps           tcp port 563   n =   740 src = "1703000018                      "  dst = "1703000018                      "
Service: nntps           tcp port 563   n =     2 src = "17030000186E                    "  encrypted

Service: ipp             tcp port 631   n =     2 src = "504F5354202F6970702F706F72743120"  dst = "485454502F312E3120323030204F4B0D"

Service: ldp             tcp port 646   n =  1760 src = "000100  86CFFD  000002  00  00  "  dst = "000100  86CFFD  0000    00  00  "
Service: ldp             udp port 646   n = 51218 src = "0001002686CFFD  00000100001C00  "  dst = "                                "

Service: kerberos-iv     udp port 750   n =    37 src = "040748414E445245572E434D552E4544"  dst = "0404    6A    00                "
Service: kerberos-iv     udp port 750   n =     8 src = "0403  6C            0000414E4452"  dst = "04    6C            0000        "
Service: kerberos-iv     udp port 750   n =     3 src = "0403              0000414E445245"  dst = "0404              0000003B9D1B  "
Service: kerberos-iv     udp port 750   n =     2 src = "04036C656A0000414E445245572E434D"  dst = "04046C656A0000003B9D1B87013B9D8C"
Service: kerberos-iv     udp port 750   n =     2 src = "0403        0000414E445245572E43"  dst = "0404        0000003B9D1C  013B9D"
Service: kerberos-iv     udp port 750   n =     2 src = "0403        67  0000414E44524557"  dst = "0404        67  0000003B9D    01"
Service: kerberos-iv     udp port 750   n =     2 src = "0403          0000414E445245572E"  dst = "0404          0000003B9D    013B"
Service: kerberos-iv     udp port 750   n =    11 src = "                                "  dst = "7E81  3081  A003020105A10302011E"
Service: kerberos-iv     udp port 750   n =    10 src = "                                "  dst = "  8202  308202  A003020105A10302"
Service: kerberos-iv     udp port 750   n =     6 src = "  82    3082    A103020105A20302"  dst = "  8202  308202  A003020105A10302"
Service: kerberos-iv     udp port 750   n =     3 src = "6A819F30819CA103020105A20302010A"  
Service: kerberos-iv     udp port 750   n =     2 src = "6C8202  308202  A103020105A20302"  dst = "6D82023630820232A003020105A10302"
Service: kerberos-iv     udp port 750   n =     1 src = "6C82026A30820266A103020105A20302"  dst = "7E81C73081C4A003020105A10302011E"
Service: kerberos-iv     udp port 750   n =     1 src = "6C82026A30820266A103020105A20302"  dst = "7E81C73081C4A003020105A10302011E"
Service: kerberos-iv     udp port 750   n =     2 src = "6C8202  308202  A103020105A20302"  dst = "6D8202  308202  A003020105A10302"
Service: kerberos-iv     udp port 750   n =     1 src = "6A81AA3081A7A103020105A20302010A"  dst = "6B82023F3082023BA003020105A10302"
Service: kerberos-iv     udp port 750   n =     1 src = "6A81AA3081A7A103020105A20302010A"  dst = "6B82023F3082023BA003020105A10302"
Service: kerberos-iv     udp port 750   n =     1 src = "6A81B93081B6A103020105A20302010A"  dst = "6B8202613082025DA003020105A10302"
Service: kerberos-iv     udp port 750   n =     1 src = "6A8201633082015FA103020105A20302"  dst = "6B82025430820250A003020105A10302"
Service: kerberos-iv     udp port 750   n =     3 src = "6A8201633082015FA103020105A20302"  dst = "7E81B33081B0A003020105A10302011E"
Service: kerberos-iv     udp port 750   n =     2 src = "6C82024D30820249A103020105A20302"  dst = "6D82021F3082021BA003020105A10302"
Service: kerberos-iv     udp port 750   n =     1 src = "6A8201633082015FA103020105A20302"  
Service: kerberos-iv     udp port 750   n =     1 src = "6C8202613082025DA103020105A20302"  

Service: imaps           tcp port 993   n =    78 src = "17030100                        "  dst = "1703010040                      "  
Service: imaps           tcp port 993   n =    12 src = "17030100                        "  dst = "1703010030                      "  
Service: imaps           tcp port 993   n =     8 src = "17030100                        "  dst = "1703010025                      "  
Service: imaps           tcp port 993   n =     7 src = "17030100                        "  dst = "1703010020                      "  
Service: imaps           tcp port 993   n =     9 src = "160301005B010000570301          "  dst = "160301004A0200004603013B9D      "
Service: imaps           tcp port 993   n =     7 src = "807A0103010051000000200000160000"  dst = "160301004A0200004603013B9D      "

Service: pop3s           tcp port 995   n =   963 src = "    01        00                "  dst = "160301004A0200004603013D        "

Service: kpop            tcp port 1109  n =   838 src = "431C0000000000000000000000000000"  
Service: kpop            tcp port 1109  n =    87 src = "000000134B5242355F53454E44415554"  
Service: kpop            tcp port 1109  n =     2 src = "7463705F646973636F6E6E6500000000"  

Service: kazaa           tcp port 1214  n = 40099 src = "80        000000                "
Service: kazaa           tcp port 1214  n = 27311 src = "4749564520  39  38    35  0D0A  "  dst = "474554202F                      "
Service: kazaa           tcp port 1214  n = 23163 src = "C0        000000                "
Service: kazaa           tcp port 1214  n = 18275 src = "80        80        000043090000"
Service: kazaa           tcp port 1214  n =  2749 src = "80        80        80        00"
Service: kazaa           tcp port 1214  n =  1396 src = "A0330D0A                        "
Service: kazaa           tcp port 1214  n =  1138 src = "C0        C0        0000        "
Service: kazaa           tcp port 1214  n =  1131 src = "80        80        80        80"
Service: kazaa           tcp port 1214  n =   412 src = "                        43050000"  dst = "            02              0000"
Service: kazaa           tcp port 1214  n =   372 src = "C0        C0        C0        00"
Service: kazaa           tcp port 1214  n =    62 src = "C0      A5C0      A5            "
Service: kazaa           tcp port 1214  n =    57 src = "C0    07  C0    07              "
Service: kazaa           tcp port 1214  n =    53 src = "C0      AFC0      AF            "
Service: kazaa           tcp port 1214  n =    49 src = "C0      7BC0      7B            "
Service: kazaa           tcp port 1214  n =    12 src = "80            A1  7B          A7"
Service: kazaa           tcp port 1214  n =    10 src = "80  3B              74      9C  "
Service: kazaa           tcp port 1214  n =    10 src = "80          A8  2582            "

Service: search-agent    tcp port 1234  n =     6 src = "01FF090001000000333AC10100C82ECE"  dst = "A3A2A1FF000000000000000000000000"
Service: imtc-mcs        tcp port 1503  n =     4 src = "0300001914E00000    00C0010DC109"  dst = "0300001510D0        00C208100005"

Service: nkd             tcp port 1650  n =    31 src = "68  3133              0000000000"

Service: h323hostcall    tcp port 1720  n =     2 src = "030000E008021C  05040388C0A5280C"
Service: pptp            tcp port 1723  n =    27 src = "474554202F6765742F3438352F646F62"  dst = "485454502035303320546F6F206D616E"
Service: ms-streaming    tcp port 1755  n =     9 src = "010000  CEFA0BB0  0000004D4D5320"  dst = "010000  CEFA0BB0700000004D4D5320"
Service: ms-streaming    tcp port 1755  n =     2 src = "474554202F696D616765732F6F6E652E"  dst = "485454502F312E3120  30  20      "
Service: msnp            tcp port 1863  n =     5 src = "414E5320    20696F776E40686F746D"  dst = "49524F20    20312031206F67696861"
Service: msnp            tcp port 1863  n =     4 src = "5645522038                      "  dst = "5645522038                      "
Service: msnp            tcp port 1863  n =     2 src = "5645522031204D534E50  204D534E50"  dst = "5645522031204D534E50  204D534E50"

Service: zephyr-clt      udp port 2103  n =    15 src = "5A455048302E32003078303030303030"  dst = "5A455048302E32003078303030303030"
Service: ici             tcp port 2200  n =     4 src = "B4840000002C830200E0840200C18502"  dst = "B534830205E0840301C10085023E8086"
Service: groove          tcp port 2492  n =     5 src = "0185000102006470703A2F2F72303938"  dst = "0248000102000000016470703A2F2F72"

Service: tivoconnect     udp port 2190  n =  3221 src = "7469766F636F6E6E6563743D310A7377"  dst = "                                "  

Service: ssc-agent       udp port 2967  n =     2 src = "00  0000  C0010300000000        "  dst = "00  0001  C04A0100000000        "

Service: hbci            tcp port 3000  n =     3 src = "0D0A      0D0A  0D0A    0A6D6B65"  dst = "2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D"
Service: hbci            tcp port 3000  n =     2 src = "0D0A        0D0A430D0A340D0A310D"  dst = "2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D"

Service: krb524          udp port 4444  n =   285 src = "61                              "  dst = "00000000000000  000000          "
Service: rsip            tcp port 4555  n =     2 src = "3134323733323831304E494C0A0A3C73"  dst = "6E6F7468696E670D0A      68696E67"

Service: aol             tcp port 5190  n =  6406 src = "2A      0000                    "
Service: aol             tcp port 5190  n =   203 src = "2A01    01080000000100060100    "  dst = "2A      00  00  00              "
Service: aol             tcp port 5190  n =   139 src = "2A01        0000000100          "  dst = "2A01    0004000000012A          "
Service: aol             tcp port 5190  n =    14 src = "2A      00  00  00          00  "  dst = "2A      00  00  00          00  "
Service: aol             tcp port 5190  n =    10 src = "2A01    0004000000012A02    0016"  dst = "2A01    0004000000012A02    00  "

Service: rfb             tcp port 5911  n =    10 src = "52464220      2E      0A        "  dst = "52464220      2E      0A        "

Service: x11             tcp port 6000  n =    59 src = "    00  016000              00  "  dst = "                000000      00  "
Service: x11             tcp port 6000  n =    56 src = "  0000      00  00  00          "  dst = "01      000000              00  "
Service: x11             tcp port 6000  n =    38 src = "4C    001A00      00            "  dst = "                3A000000  00    "
Service: x11             tcp port 6000  n =    30 src = "6C000B000000  00  000000        "  dst = "    0B000000  00                "
Service: x11             tcp port 6000  n =    25 src = "    0005    00      00  00      "  dst = "            00  0000      00    "
Service: x11             tcp port 6000  n =    21 src = "    00  01  00  01  00  01  00  "  dst = "            00  0000        00  "
Service: x11             tcp port 6000  n =    20 src = "7F000001    00                  "  dst = "            0001    000100      "
Service: x11             tcp port 6000  n =    20 src = "    00      00    0000      00  "  dst = "                000000      00  "
Service: x11             tcp port 6000  n =    14 src = "    000500  0015                "  dst = "                0000005500  00  "
Service: x11             tcp port 6000  n =    13 src = "      00      00      00  00E0  "  dst = "                  000000  00    "
Service: x11             tcp port 6000  n =    10 src = "4C  00      001A    00          "  dst = "                000000      001A"
Service: x11             tcp port 6000  n =     5 src = "4C  00      00      00      01  "  dst = "                00000055    00  "
Service: x11             tcp port 6000  n =     7 src = "46  07001900    1400    0000FFFF"  dst = "  00    1800      00    00      "
Service: x11             tcp port 6000  n =     8 src = "    0100    0100      00        "  dst = "                  000000  00    "
Service: x11             tcp port 6000  n =     2 src = "    00    0000    0000          "  dst = "002D000B0000000C436C69656E742069"
Service: x11             tcp port 6000  n =     7 src = "          6000    6000      00  "  dst = "        00      00  00  00      "
Service: x11             tcp port 6000  n =     7 src = "    00      00  02  00      00  "  dst = "0100    000000030000002300010001"
Service: x11             tcp port 6000  n =     3 src = "  0000  054000  054000  00      "  dst = "    0A          00  00      00  "
Service: x11             tcp port 6000  n =     6 src = "    0400  00      00          00"  dst = "                  000000  00    "
Service: x11             tcp port 6000  n =     6 src = "  0000  05  00      00          "  dst = "        05  00      00  00      "
Service: x11             tcp port 6000  n =     1 src = "7F0201007F020100"                  dst = "                                "
Service: x11             tcp port 6000  n =     1 src = "140106000100A0019F0100001F000000"  dst = "1C8CE9000100A0019F01000045A1B590"
Service: x11             tcp port 6000  n =     2 src = "  01  00  00  03  00  03  00    "  dst = "          00  03        01    00"
Service: x11             tcp port 6000  n =     4 src = "02  04001A00  03040000002A00  03"  dst = "0600            3A0000001A00  03"
Service: x11             tcp port 6000  n =     8 src = "    0001    0001    00      00  "  dst = "                000000      00  "
Service: x11             tcp port 6000  n =     2 src = "    00      00    0000  00  00  "  dst = "        00  00  0000            "
Service: x11             tcp port 6000  n =     5 src = "    00  00  00  00  00  00  00  "  dst = "                00  00  00  00  "
Service: x11             tcp port 6000  n =     2 src = "  0000      00  00  02      00  "  dst = "                000000      00  "
Service: x11             tcp port 6000  n =     2 src = "  000008    00              00  "  dst = "  00              8000      00  "
Service: x11             tcp port 6000  n =     4 src = "42  000B00000012001000004D49542D"  dst = "    000B000000                  "
Service: x11             tcp port 6000  n =     1 src = "41E80000001000463F3BBBBC3F0CCCCC"  dst = "010007B8000000040000000000000004"

Service: dtspcd          tcp port 6112  n =     4 src = "01  0001  000000                "  dst = "07000100000000        00  00  00"

Service: gnutella-svc    tcp port 6346  n =  1859 src = "474554202F6765742F  2F          "  dst = "485454502F312E  2035303320      "
Service: gnutella-svc    tcp port 6346  n =  1755 src = "474E5554454C4C4120434F4E4E454354"  dst = "474E5554454C4C41204F4B0A0A00    "
Service: gnutella-svc    tcp port 6346  n =    18 src = "4749562037393A394541383837384245"  dst = "474554202F6765742F    2F        "
Service: gnutella-svc    tcp port 6346  n =     7 src = "474956203132383A4342433330394134"  dst = "474554202F6765742F3132382F546865"
Service: gnutella-svc    tcp port 6346  n =     3 src = "3804A9D78F69254CACF09A0F670B56B0"  
Service: gnutella-svc    tcp port 6346  n =     3 src = "47495620353632333A36324134413144"  
Service: gnutella-rtr    tcp port 6347  n =   156 src = "474554202F6765742F33            "  dst = "485454502F312E312035303320536572"
Service: gnutella-rtr    tcp port 6347  n =   123 src = "474E5554454C4C4120434F4E4E454354"  dst = "474E5554454C4C41204F4B0A0A      "

Service: irc             tcp port 6699  n =     6 src = "434C4945  00                    "  dst = "31000000"
Service: irc             tcp port 6699  n =     4 src = "434D4E44        B5              "  dst = "31      "
Service: irc             tcp port 6699  n =     4 src = "53454E44  65                    "  dst = "31      "
Service: irc             tcp port 6699  n =     3 src = "434D4E44434D4E44                "  dst = "31                              "
Service: irc             tcp port 6699  n =     2 src = "434D4E44                  37    "  dst = "31      "
Service: irc             tcp port 6699  n =     2 src = "434D4E44                      EA"  dst = "31                              "
Service: irc             tcp port 6699  n =     2 src = "434D4E4497                      "  dst = "31                              "
Service: irc             tcp port 6699  n =     2 src = "434D4E44                  42    "  dst = "31      "

Service: afs3-fileserver udp port 7000  n =   313 src = "        EE      0000000100000001"  dst = "        EE      0000000100000001"
Service: afs3-callback   udp port 7001  n =   349 src = "        EE      000000  00000001"  dst = "        EE      000000  00000001"

Service: afs3-prserver   tcp port 7002  n =     3 src = "0C000000CA0000000100000075000000"  dst = "84000000CA0000000200000000007400"
Service: afs3-prserver   tcp port 7002  n =     3 src = "000000  0000006400              "  dst = "000000  00000019000000  000000  "

Service: afs3-prserver   udp port 7002  n =   395 src = "                000000  00000001"  dst = "                000000  000000  "
Service: afs3-prserver   udp port 7002  n =   159 src = "                0000000100000001"  dst = "                000000  000000  "
Service: afs3-prserver   udp port 7002  n =    23 src = "                000000  00000001"  dst = "                000000  00000001"
Service: afs3-prserver   udp port 7002  n =     5 src = "3D      F7      0000000100000001"  dst = "3D      F7      0000000100000001"
Service: afs3-prserver   udp port 7002  n =     5 src = "3D      F7      0000000100000001"  dst = "3D      F7      0000000100000001"
Service: afs3-prserver   udp port 7002  n =     1 src = "3DFE12D7F7DAEF500000000100000001"  dst = "3DFE12D7F7DAEF50 000000010000000"

Service: afs3-vlserver   udp port 7003  n =   253 src = "        EE      0000000100000001"  dst = "        EE      0000000100000001"
Service: afs3-kaserver   udp port 7004  n =     3 src = "3B9D1C  EE      0000000100000001"  dst = "3B9D1C  EE      0000000100000001"
Service: afs3-volser     udp port 7005  n =     3 src = "3B9D1D  EE      0000000100000001"  dst = "3B9D1D  EE      0000000100000001"

Service: ups-onlinet     udp port 7010  n =    30 src = "                000000  00000001"  dst = "                0000000000000000"
Service: ups-onlinet     udp port 7010  n =    39 src = "                000000  000000  "  dst = "                000000  000000  "

Service: arcp            tcp port 7070  n =     4 src = "504E41000A000100021B  0014000200"  dst = "504E41000A            00071A7200"
Service: arcp            tcp port 7070  n =     3 src = "474554202F72616D67656E2F77647571"  dst = "485454502F312E3020323030204F4B0D"

Service: irdmi           tcp port 8000  n =    58 src = "47455420  74                    "  dst = "485454502F312E3120323030204F4B0D"
Service: irdmi           tcp port 8000  n =    14 src = "474554202F696D616765732F5465656E"  dst = "485454502F312E3020  30  20      "
Service: vcom-tunnel     tcp port 8001  n =    56 src = "474554202F                      "  dst = "48545450        20              "
Service: vcom-tunnel     tcp port 8001  n =     4 src = "504F5354202F6367692D62696E2F6272"  dst = "485454502F312E302032303020446F63"
Service: http-alt        tcp port 8080  n =    34 src = "474554202F                      "  dst = "485454502F312E3120  30  20      "
Service: http-alt        tcp port 8080  n =     2 src = "47455420687474703A2F2F7777772F64"  
Service: ultraseek-http  tcp port 8765  n =     6 src = "474554202F                      "  dst = "485454502F312E3020323030204F4B0D"
Service: ddi-tcp-1       tcp port 8888  n =     2 src = "230002006D6F6E695F6C75765F20346D"  dst = "  000000546869732073657276657220"
Service: cslistener      udp port 9000  n =     6 src = "32000000    01005818            "  dst = "  040000              0000      "

Service: ndmp            udp port 10000 n =   824 dst = "3120322E302E302067696E6765722E63"
Service: ndmp            udp port 10000 n =    30 src = "5CEF52D20000                    "  dst = "4AC302960000                    "
Service: ndmp            udp port 10000 n =    22 src = "FFFFFFFF5CEF52D20000            "  dst = "4AC302960000                    "
Service: ndmp            udp port 10000 n =    25 src = "FFFFFFFFFFFF                    "  dst = "4AC302960000                    "
Service: ndmp            udp port 10000 n =    28 src = "FFFF5CEF52D20000                "  dst = "4AC302960000                    "

Service: Quake           udp port 27006 n =   533 src = "FFFFFFFF          FFFFFF        "  dst = "FFFFFFFF              31    2E  "
Service: Quake           udp port 27006 n =    91 src = "FFFFFFFF              00"          dst = "FFFFFFFF        2E322E3134362E31"
Service: Quake           udp port 27007 n =   527 src = "FFFFFFFF            FFFFFF      "  dst = "FFFFFFFF        2E322E3134362E31"
Service: Quake           udp port 27007 n =    64 src = "FFFFFFFF70            00"          dst = "FFFFFFFF  000000"
Service: Quake           udp port 27025 n =    17 src = "FFFFFFFF70696E6700FFFFFFFF646574"  dst = "FFFFFFFF6A00FFFFFFFF6D          "

Service: ypserv          tcp port 32771 n =   436 src = "800000          0000000000000002" 

Service: ypserv          udp port 1023  n =   634 src = "        0000000000000002000186A4"  
Service: ypserv          udp port 1023  n =   234 src = "3D8D    0000000000000002000186A4"  dst = "3D8D    000000000000000000000000"
Service: ypserv          udp port 1023  n =    15 src = "3D8F    0000000000000002000186A4"  dst = "3D8F    000000010000000000000000"
