#!/bin/sh
# postinst script for argus
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
     if [ -x "/etc/init.d/radium" ]; then
#	update-rc.d radium defaults 56 44 >/dev/null 
 	update-rc.d radium disable  >/dev/null 2>&1
     fi
     if [ -x "/etc/init.d/rasplit" ]; then
#	update-rc.d rasplit defaults 57 43 >/dev/null 
 	update-rc.d rasplit disable  >/dev/null 2>&1
     fi
     exit 0
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
