#!/bin/sh
# Build the ArgusHandleRecord fuzz harness against the real client-library object files.
#
# Prerequisite: the client tree must already be configured (./configure) so that
# include/argus_config.h exists. This script does NOT run configure itself.
#
# Usage:
#   security-review/fuzz/build.sh            # AFL++ persistent-mode instrumented build
#   security-review/fuzz/build.sh plain      # plain clang build (no AFL instrumentation,
#                                               used by CI to replay saved inputs quickly)

set -e

cd "$(dirname "$0")/../.."   # repo root (argus/clients)

REPO_ROOT="$(pwd)"
FUZZ_DIR="$REPO_ROOT/security-review/fuzz"
BUILD_DIR="$FUZZ_DIR/build"

mkdir -p "$BUILD_DIR"

if [ ! -f include/argus_config.h ]; then
   echo "error: include/argus_config.h not found -- run ./configure first" >&2
   exit 1
fi

MODE="${1:-afl}"

if [ "$MODE" = "afl" ]; then
   CC=afl-clang-fast
else
   CC=clang
fi

INCLUDE_DIRS="-I. -Iinclude -Icommon"
if [ -d /opt/homebrew/include ]; then
   INCLUDE_DIRS="$INCLUDE_DIRS -I/opt/homebrew/include"
fi
if [ -d /opt/homebrew/opt/mysql-client/include/mysql ]; then
   INCLUDE_DIRS="$INCLUDE_DIRS -I/opt/homebrew/opt/mysql-client/include/mysql"
fi

CFLAGS="-O1 -g -fno-omit-frame-pointer -DHAVE_CONFIG_H $INCLUDE_DIRS"
# AddressSanitizer/UBSan are essential here -- the bug classes found in this review's static
# and dynamic analysis phases (heap-buffer-overflow, unchecked-allocation NULL derefs, etc.)
# are exactly what these sanitizers are built to catch.
#
# UBSan's "alignment" check is deliberately EXCLUDED: Argus records are read directly off the
# wire/file into buffers that are not guaranteed to be aligned relative to every DSR struct
# they're cast to -- this is universally tolerated, expected behavior in this codebase on
# x86/ARM64 (both tolerate unaligned loads transparently) and would otherwise drown every run
# in irrelevant noise before reaching a real bug.
CFLAGS="$CFLAGS -fsanitize=address,undefined -fno-sanitize=alignment -fno-sanitize-recover=all"

echo "Compiling client-library object files needed by the harness (mode=$MODE, CC=$CC)..."

# Object files required by ArgusHandleRecord's full call graph. Mirrors common/Makefile.in's
# COMMONOBJ + CLIENTOBJ + EVENTOBJ + TIMEROBJ lists exactly (minus argus_main.c, which has
# main() -- the harness supplies its own -- and minus argus_windows_registry.c, which is
# Windows-only and excluded from this platform's build).
LIB_SRCS="
common/argus_code.c
common/argus_filter.c
common/argus_util.c
common/argus_auth.c
common/argus_parser.c
common/argus_lockfile.c
common/argus_clientconfig.c
common/argus_parse_time.c
common/version.c
common/argus_client.c
common/argus_import.c
common/argus_label.c
common/argus_grep.c
common/argus_label_geoip.c
common/argus_output.c
common/argus_json.c
common/ring.c
common/argus_split_mode.c
common/argus_event.c
common/argus_timer.c
"

# grammar.y/scanner.l need bison/flex to regenerate grammar.c/scanner.c -- mirrors the real
# rules in common/Makefile exactly (LEX = "flex -Pargus_", YACC = "bison -y -p argus_").
if [ ! -f common/grammar.c ] || [ ! -f common/scanner.c ] || [ ! -f common/tokdefs.h ]; then
   echo "Generating common/grammar.c, tokdefs.h, and common/scanner.c via bison/flex..."
   ( cd common && rm -f grammar.c tokdefs.h && bison -y -p argus_ grammar.y -d && mv y.tab.c grammar.c && mv y.tab.h tokdefs.h )
   ( cd common && rm -f scanner.c && flex -Pargus_ -t scanner.l > scanner.c )
fi
LIB_SRCS="$LIB_SRCS common/grammar.c common/scanner.c"

# version.c is also gitignored and normally generated by common/Makefile.in's rule
# (sed over the top-level VERSION file) as part of a full "make" -- regenerate it here too,
# since this script never runs the full Makefile-driven build.
if [ ! -f common/version.c ]; then
   echo "Generating common/version.c from VERSION..."
   sed -e 's/.*/char version[] = "&";/' VERSION > common/version.c
fi

OBJS=""
for src in $LIB_SRCS; do
   obj="$BUILD_DIR/$(basename "$src" .c).o"
   echo "  CC $src"
   if [ "$(basename "$src")" = "grammar.c" ]; then
      $CC $CFLAGS -Dyylval=argus_lval -c "$src" -o "$obj"
   else
      $CC $CFLAGS -c "$src" -o "$obj"
   fi
   OBJS="$OBJS $obj"
done

echo "Compiling harness..."
$CC $CFLAGS -c "$FUZZ_DIR/fuzz_handle_record.c" -o "$BUILD_DIR/fuzz_handle_record.o"

LIBDIRS=""
LIBS="-lz -lm"
if [ -d /opt/homebrew/lib ]; then
   LIBDIRS="$LIBDIRS -L/opt/homebrew/lib"
fi
if [ -d /opt/homebrew/opt/mysql-client/lib ]; then
   LIBDIRS="$LIBDIRS -L/opt/homebrew/opt/mysql-client/lib"
fi
# libmaxminddb/readline/ncurses/mysqlclient are all conditionally used by common/argus_*.c
# depending on how ./configure detected the platform; link them unconditionally here since
# this harness is only ever built on systems where ./configure has already succeeded (i.e.
# these libraries are known to be present).
LIBS="$LIBS -lmaxminddb -lreadline -lncurses"

echo "Linking..."
$CC $CFLAGS \
   "$BUILD_DIR/fuzz_handle_record.o" $OBJS \
   $LIBDIRS $LIBS \
   -o "$FUZZ_DIR/fuzz_handle_record"

echo "Built: $FUZZ_DIR/fuzz_handle_record"
