.\" Copyright (c) 2000-2016 QoSient, LLC
.\" All rights reserved.
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2, or (at your option)
.\" any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH RACONVERT 1 "07 October 2003" "raconvert 3.0.8"
.SH NAME
\fBraconvert\fP \- convert comma-separated ASCII \fBargus(8)\fP data, to binary \fBargus(8)\fP data.
.SH SYNOPSIS
.B raconvert
\fB\-r\fP \fIinput\fP \fB\-w\fP \fIoutput\fP
.SH DESCRIPTION
.IX  "raconvert command"  ""  "\fLraconvert\fP \(em argus data"
.LP
.B Raconvert
reads comman separated ASCII
.BR argus
data from a file or stdin, and converts the ASCII representation to binary format.
In order for \fBraconver\fP to process the delimited data correctly, the file should
be created by \fBra.1\fP like programs, using the "-c <char>" option to specify
a field separator.  Column delimiters can be any non-ambiguous character, and are
automatically discovered from the files title string.

Because \fBraconvert.1\fP expects the first valid string in the file to be a
\fBra.1\fP column title line, the \fBra.1\fP program must use the equivalent
of the "-L 0" option.  

The file can present its column oriented data in any order, and \fBraconvert\fP will
accomodate.  Duplicate columns on the same line are allowed, but the final value
in the resulting argus record with be the last value encountered.

\fBraconvert.1\fP can read gzip and bzip2 compressed files, based on the file extension.

.SH USES
.B Raconvert
is predominately used for reading ASCII represented archive data.  Argus data is
routinely converted to ASCII for inspection and archiving, due to the good
compressibility offered by gzip and others.  Argus data is also converted from binary
to ASCII and back to binary, as a routine process to enforce content policies.
The conversion, with ASCII inspection ensures that specific data of interest isn't
leaked.

.SH INVOCATION
.nf
\fBra\fP -L0 c , -r argusfile > argus.ascii.csv 
\fBraconvert\fP -r argus.ascii.csv -w argusfile
.fi

.SH COPYRIGHT
Copyright (c) 2000-2016 QoSient. All rights reserved.
.SH SEE ALSO
.BR ra(1),
.BR rarc(5),
.BR argus(8),
.SH FILES

.SH AUTHORS
.nf
Carter Bullard (carter@qosient.com).
.fi
.SH BUGS
