.\"
.\" Argus-5.0 Software
.\" Copyright (c) 2000-2024 QoSient, LLC
.\" All rights reserved.
.\"
.\"
.TH RACONVERT 1 "07 October 2023" "raconvert 5.0.3"
.SH NAME
\fBraconvert\fP \- convert comma-separated ASCII \fBargus(8)\fP data, to binary \fBargus(8)\fP data.
.SH SYNOPSIS
.B raconvert
\fB\-r\fP \fIinput\fP \fB\-w\fP \fIoutput\fP
.SH DESCRIPTION
.IX  "raconvert command"  ""  "\fLraconvert\fP \(em argus data"
.LP
.B Raconvert
reads ASCII based files, either CSV, or Json 
.BR argus
data from a file or stdin, and converts the ASCII representation to binary
argus format.  In order for \fBraconvert\fP to process the data correctly, the file should
be created by \fBra.1\fP like programs, using the "-c <char>" option or the "-M json"
mode, to specify the ASCII format.  In the case of CSV files, column delimiters can be
any non-ambiguous character, and are automatically discovered from the files title string.

In the case of CSV files, because \fBraconvert.1\fP expects the first valid string in the
file to be a \fBra.1\fP column title line, the \fBra.1\fP program must use the equivalent
of the "-L 0" option.  

The file can present its column oriented data in any order, and \fBraconvert\fP will
accomodate.  Duplicate columns on the same line are allowed, but the final value
in the resulting argus record with be the last value encountered.

\fBraconvert.1\fP can read gzip and bzip2 compressed files, based on the file extension.

.SH USES
.B Raconvert
is predominately used for reading ASCII represented archive data.  Argus data is
routinely converted to ASCII for inspection and archiving, due to the good
compressibility offered by gzip and others.  Argus data is also converted from binary
to ASCII and back to binary, as a routine process to enforce content policies.
The conversion, with ASCII inspection ensures that specific data of interest isn't
leaked.

.SH INVOCATION
.nf
\fBra\fP -L0 -c , -r argusfile > argus.ascii.csv 
\fBraconvert\fP -r argus.ascii.csv -w argusfile
.fi

.nf
\fBra\fP -M json -r argusfile > argus.json
\fBraconvert\fP -r argus.json -w argusfile
.fi

.SH COPYRIGHT
Copyright (c) 2000-2024 QoSient. All rights reserved.
.SH SEE ALSO
.BR ra(1),
.BR rarc(5),
.BR argus(8),
.SH FILES

.SH AUTHORS
.nf
Carter Bullard (carter@qosient.com).
.fi
.SH BUGS
