.\"
.\" Argus-5.0 Software
.\" Copyright (c) 2000-2024 QoSient, LLC
.\" All rights reserved.
.\"
.\"
.TH RALABEL 1 "12 August 2023" "ralabel 5.0.3"
.SH NAME
\fBralabel\fP \- inserts fixed form or free form metadata labels into \fBargus(8)\fP.
\fBralabel\fP supports a number of strategies for labeling including 1) address based,
providing free form metadata, country code, geo data and fully qualified domain name
(FQDN) labeling; 2)port based, providing free form labels using IANA port definitions,
and 3) flow filter, providing free form labels based on argus filter specicfications.


.SH SYNOPSIS
.B ralabel
\fB\-f\fP \fIaddress.file\fP [-M \fBaddr\fP] [-m \fBmask\fP] [\fBraoptions\fP] [\fB--\fP \fIfilter-expression\fP]
.SH DESCRIPTION
.IX  "ralabel command"  ""  "\fBralabel\fP \(em argus data"
.LP
\fBRalabel\fP reads
.BR argus
data from an \fIargus-data\fP source, and selects records that include IP addresses
specified by the \fBaddress.spec\fP file.  This program provides high performance
address matching for any number of addresses.

.SH RALABEL ADDRESS SPECIFICATION
Ralabel, reads a number of standard IANA IP address file formats that
specific IPv4 addresses, CIDR addresses and IPV4 prefix address specification.
Examples of these file types are provided in ./support/Config.

.LP
.SH OPTIONS
.TP 4 4
.BI \-f "\| label.strategy.specification.file\^"
Provide a label specification file.
.TP 4 4
.BI \-M "\| addr\^"
If the label specification is a simple address list, specify this option.
.TP 4 4
.BI \-m "\| saddr, daddr\^"
For IANA address labeling, specify which address should be labeled (default saddr and daddr).

.SH INVOCATION
This invocation reads \fBargus(8)\fP data from \fBargusfile\fP and labels
records that match any options in the \fBralabel.conf\fP file.
.nf
 
   \fBralabel\fP -r argusfile -f ralabel.conf - ip
 
.fi

.SH COPYRIGHT
Copyright (c) 2000-2024 QoSient. All rights reserved.

.SH SEE ALSO
.BR ralabel.conf.5,
.BR ra(1),
.BR rarc(5),
.BR argus(8),

.SH AUTHORS
.nf
Carter Bullard (carter@qosient.com).
.fi
